### ISSUE TITLE
Running on iOS10, I found an error

### ISSUE THREAD

**Issue by yuzhiyou1990** [polkadot-js/common#432] opened 2019-07-05 10:13 UTC
![image](https://user-images.githubusercontent.com/3783037/60716527-36fa0380-9f52-11e9-8772-f86c39ffed88.png)
URL:
https://polkadot.js.org/apps/#/accounts

**Comment by Stefie** [comment] 2019-07-05 11:09
Closing because it's a duplicate of https://github.com/polkadot-js/apps/issues/1362

**Closed by Stefie** 2019-07-05 11:09 UTC
