### ISSUE TITLE
React Native - Conversion from 'BigInt' to 'number' is not allowed (IOS)

### ISSUE THREAD

**Issue by ILoomans** [polkadot-js/common#1522] opened 2022-06-10 11:12 UTC
# Problem 

I know that this issue has been addressed earlier but it seems all of the issues get closed down before an actual resolution is found for react native.

* I have only experienced this issue on IOS
Essentially as my react-native app loads I connect to a websocket:

`
    import '@polkadot/wasm-crypto/cjs/initOnlyAsm';
    const types = {Address: 'MultiAddress', LookupSource: 'MultiAddress'};
    const wsProvider = new WsProvider('wss://rpc.polkadot.io');
    const api = await ApiPromise.create({provider: wsProvider, types});

`
Here are my initial dependencies

`
    "@polkadot/api": "^7.5.1",
    "@polkadot/api-contract": "^7.5.1",
    "@polkadot/reactnative-identicon": "^1.4.1",
    "@polkadot/types": "^7.5.1",
    "@polkadot/util": "^8.7.1",
    "@polkadot/util-crypto": "^8.7.1",
    "@polkadot/wasm-crypto": "^5.1.1",
`

This is quickly followed by the warning:
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[13], "@polkadot/util-crypto").blake2AsU8a')

And then the error message:

Conversion From 'BigInt' to 'number' is not allowed

### Upgrading packages #1465 

In here the suggestion is that I should upgrade the polkadot.js/common packages, however I was unsuccesfull in doing this.
Here are my dependencies, the exact same error showed up
`
    "@polkadot/api": "^8.4.2",
    "@polkadot/api-contract": "^8.4.2",
    "@polkadot/reactnative-identicon": "^2.2.1",
    "@polkadot/types": "^8.4.2",
    "@polkadot/util": "^9.2.1",
    "@polkadot/util-crypto": "^9.2.1",
    "@polkadot/wasm-crypto": "^6.1.1",
`

### Modifying babel.config.js #1324 (url)
Tell me if im wrong but the proposed solution is a link to https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-929362393 , which from by best understanding is a solution for how to fix this in React, not react-native.

## Potential Solution

It seems like stylo app has a working basis for a polkadot.js app, but i still need to test it this weekend.
https://github.com/stylo-app/stylo

**Comment by jacogr** [comment] 2022-06-10 11:33
Your libraries are very outdated in this case. (Old version != current version)

**Comment by ILoomans** [comment] 2022-06-10 11:46
Thanks for the response

I tried upgrading it to the dependencies seen in #1465 
Still got the same error.  Just some background on why I am using older versions is because the new versions don't seem to be compatable with the substrate 4.0.0-dev node. For example when i upgrade I cant interact with the the contract pallet (but this is a seperate issue).

If you could point me in the right direction with these links on how to fix it, it would be well appreciated, I think it would be useful for other people who seem to have gotten stuck here

**Comment by ILoomans** [comment] 2022-06-11 14:36
Ive been looking deeper into this. I can confirm that this problem arrives at version v6.0.1 of @polkadot/api package (based off of the @polkadot/common dependencies it has). In v5.9.1 the problem is not experienced! I'll look into this deeper later this weekend!

https://github.com/polkadot-js/common/commit/4b097dcaeffaf5e7dbe10e9e28404f6ff009139d
https://github.com/polkadot-js/api/commit/0865b91f885f3b6d584bd4a5048b4265924d1eab

**Comment by jacogr** [comment] 2022-06-11 15:21
6.1.1 is very different to 6.0.1, see the CHANGELOG (the whole init phase has been completely re-done). 6.0.1 was the first introduction of split (where 6.1.1 aligned again with the old process)

In these cases it really doesn't help looking at "old" since between the 3 versions mentioned here, the process is vastly different. (With some similarities between 6.1.x and 5.x, 6.0 being the outlier)

**Comment by jacogr** [comment] 2022-06-11 15:31
Duplicate of https://github.com/polkadot-js/common/issues/1321, https://github.com/polkadot-js/common/issues/1324, https://github.com/polkadot-js/common/issues/1330 (with Babel config resolutions)

**Comment by ILoomans** [comment] 2022-06-14 09:44
Thanks for this!

I found a solution that I think people will find valuable. 

I was using metro-react-native-babel-preset in my babel.config.js

Indeed i had to disable '@babel/plugin-transform-exponentiation-operator'

i did this with patch packages by just commenting out the plugin!


diff --git a/node_modules/metro-react-native-babel-preset/src/configs/main.js b/node_modules/metro-react-native-babel-preset/src/configs/main.js
index 6d25b29..f76fb29 100644
--- a/node_modules/metro-react-native-babel-preset/src/configs/main.js
+++ b/node_modules/metro-react-native-babel-preset/src/configs/main.js
@@ -124,11 +124,11 @@ const getPreset = (src, options) => {
     extraPlugins.push([require("@babel/plugin-transform-async-to-generator")]);
   }
 
-  if (!isHermes && (isNull || src.indexOf("**") !== -1)) {
-    extraPlugins.push([
-      require("@babel/plugin-transform-exponentiation-operator"),
-    ]);
-  }
+  // if (!isHermes && (isNull || src.indexOf("**") !== -1)) {
+  //   extraPlugins.push([
+  //     require("@babel/plugin-transform-exponentiation-operator"),
+  //   ]);
+  // }
 
   if (!isHermes && (isNull || src.indexOf("Object.assign")) !== -1) {
     extraPlugins.push([require("@babel/plugin-transform-object-assign")]);
`

`

**Closed** 2022-06-28 05:05 UTC
Labels: <duplicate>, <support>
