### ISSUE TITLE
can't compile /@polkadot/util-crypto/secp256k1/expand.js

### ISSUE THREAD

**Issue by luozygithub** [polkadot-js/common#1413] opened 2022-02-25 03:01 UTC
![image](https://user-images.githubusercontent.com/31771728/155645547-aa2adc43-b441-4fca-a5bc-ccd06f2f729c.png)

    "@polkadot/api": "^7.9.1",

**Comment by jacogr** [comment] 2022-02-25 04:33
Duplicate of https://github.com/polkadot-js/common/issues/1321, https://github.com/polkadot-js/common/issues/1324, https://github.com/polkadot-js/common/issues/1330

TL;DR This is due to your local build setup, it is not related to the library itself. The linked issues has solutions to adjust your local environment.

**Closed by jacogr** 2022-02-25 04:33 UTC
Labels: <duplicate>
