### ISSUE TITLE
Attempted import error: 'TextDecoder' is not exported from '@polkadot/x-textdecoder'

### ISSUE THREAD

**Issue by MHarisAshfaq** [polkadot-js/common#1828] opened 2023-05-07 22:16 UTC
I have added these 2 packages to my package.json file
```
"@reef-defi/evm-provider": "1.0.2",
"@reef-defi/extension-dapp": "1.0.2",
```
Now getting the below error on `yarn start` and `yarn build`
```
Failed to compile.

./node_modules/@polkadot/util/u8a/toString.js
Attempted import error: 'TextDecoder' is not exported from '@polkadot/x-textdecoder'
```

**Comment by TarikGul** [comment] 2024-10-28 22:12
This is an issue with `"@reef-defi/extension-dapp": "1.0.2",` and not this lib. I was not able to reproduce it in a blank enviornment with just PJS deps. 

Therefore closing.

**Closed by TarikGul** 2024-10-28 22:12 UTC
Labels: Support, missing info
