### ISSUE TITLE
TypeError: Conversion from 'BigInt' to 'number' is not allowed.

### ISSUE THREAD

**Issue by binkerxbc** [polkadot-js/common#1330] opened 2021-12-20 09:23 UTC
IOS14.4 or later. This error has occurred.
 I just import the library and I get this error. The program crashed.
 But in ios 13.7 it works 

   "@polkadot/api-6": "npm:@polkadot/api@^6.12.1",
   "react-native": "0.63.4",
    "react": "16.13.1",

**Comment by jacogr** [comment] 2021-12-20 11:58
Duplicate of https://github.com/polkadot-js/common/issues/1321

**Closed by jacogr** 2021-12-20 11:58 UTC
Labels: <duplicate>
